[tool.poetry]
name = "yfinanceproject"
version = "0.1.0"
description = ""
authors = ["chenhan20 <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
yfinance = "^0.1.63"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
